//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class Credentials
    {
        public string Username { get; set; }
        public string Password { get; set; }
        public bool WinLogin { get; set; }
        public bool IsAdmin { get; set; }
        public bool Enabled { get; set; }
    }
}
