//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Edmx
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataEntities : DbContext
    {
        public DataEntities()
            : base("name=DataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AreaOfAssistance> AreaOfAssistance { get; set; }
        public virtual DbSet<Credentials> Credentials { get; set; }
        public virtual DbSet<LKP_Campus> LKP_Campus { get; set; }
        public virtual DbSet<LKP_CountryOfOrigin> LKP_CountryOfOrigin { get; set; }
        public virtual DbSet<LKP_Course> LKP_Course { get; set; }
        public virtual DbSet<LKP_CourseCategory> LKP_CourseCategory { get; set; }
        public virtual DbSet<LKP_NativeLanguage> LKP_NativeLanguage { get; set; }
        public virtual DbSet<LKP_ProgramOfStudy> LKP_ProgramOfStudy { get; set; }
        public virtual DbSet<LKP_StudentServiceProgram> LKP_StudentServiceProgram { get; set; }
        public virtual DbSet<LKP_SurveyReferrer> LKP_SurveyReferrer { get; set; }
        public virtual DbSet<Login> Login { get; set; }
        public virtual DbSet<REL_Student_StudentService> REL_Student_StudentService { get; set; }
        public virtual DbSet<Student> Student { get; set; }
    }
}
