//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class REL_Student_StudentService
    {
        public int ID { get; set; }
        public int FK_Student { get; set; }
        public int FK_Program { get; set; }
        public bool IsCurrent { get; set; }
    
        public virtual LKP_StudentServiceProgram LKP_StudentServiceProgram { get; set; }
        public virtual Student Student { get; set; }
    }
}
