//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {
            this.Login = new HashSet<Login>();
            this.REL_Student_StudentService = new HashSet<REL_Student_StudentService>();
        }
    
        public int StudentID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<int> FK_NativeLanguage { get; set; }
        public Nullable<int> FK_CountryOfOrigin { get; set; }
        public Nullable<int> FK_ProgramOfStudy { get; set; }
    
        public virtual LKP_CountryOfOrigin LKP_CountryOfOrigin { get; set; }
        public virtual LKP_NativeLanguage LKP_NativeLanguage { get; set; }
        public virtual LKP_ProgramOfStudy LKP_ProgramOfStudy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Login> Login { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REL_Student_StudentService> REL_Student_StudentService { get; set; }
    }
}
