//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TLCLogin.Data {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DBSchemaTables {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DBSchemaTables() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TLCLogin.Data.DBSchemaTables", typeof(DBSchemaTables).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AreaOfAssistance.
        /// </summary>
        internal static string AreaOfAssistance {
            get {
                return ResourceManager.GetString("AreaOfAssistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campus.
        /// </summary>
        internal static string Campus {
            get {
                return ResourceManager.GetString("Campus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CountryOfOrigin.
        /// </summary>
        internal static string CountryOfOrigin {
            get {
                return ResourceManager.GetString("CountryOfOrigin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course.
        /// </summary>
        internal static string Course {
            get {
                return ResourceManager.GetString("Course", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CourseCategory.
        /// </summary>
        internal static string CourseCategory {
            get {
                return ResourceManager.GetString("CourseCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoginHistory.
        /// </summary>
        internal static string LoginHistory {
            get {
                return ResourceManager.GetString("LoginHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NativeLanguage.
        /// </summary>
        internal static string NativeLanguage {
            get {
                return ResourceManager.GetString("NativeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student_StudentService_Past.
        /// </summary>
        internal static string PastStuServices {
            get {
                return ResourceManager.GetString("PastStuServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProgramsOfStudy.
        /// </summary>
        internal static string ProgramOfStudy {
            get {
                return ResourceManager.GetString("ProgramOfStudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student.
        /// </summary>
        internal static string Student {
            get {
                return ResourceManager.GetString("Student", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student_StudentService.
        /// </summary>
        internal static string StudentStuService {
            get {
                return ResourceManager.GetString("StudentStuService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StudentServiceProgram.
        /// </summary>
        internal static string StuServiceProgram {
            get {
                return ResourceManager.GetString("StuServiceProgram", resourceCulture);
            }
        }
    }
}
